spring.application.name=customer-service

server.port=8081

management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
spring.datasource.username=root
spring.datasource.password=Manju123@Manju123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.info.env.enabled=true

info.app.name=Customer Service
info.app.version=1.0
info.app.description=Customer management backend service